# [prebuild]
#   command = "yarn prebuild"

[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-emails"